#!/bin/sh

cd ../frontend
lein run
mv bytecode.proto ../model
cd ../model

#protoc --cpp_out="../backend/protobuf" bytecode.proto # the c++ proto files are now being generated by cmake / make
protoc --clojure_out="../frontend/src" bytecode.proto