#include "MemoryManagement.h"
#include "../RuntimeHeaders.h"
#include "../bridge/Exceptions.h"
#include "../cljassert.h"
#include "../runtime/word.h"
#include "DynamicConstructor.h"
#include "LLVMTypes.h"
#include "TypedValue.h"
#include "ValueEncoder.h"
#include "VariableBindings.h"
#include "llvm/ADT/StringSwitch.h"
#include <cstdint>
#include <llvm/IR/Constants.h>
#include <string>

using namespace llvm;

namespace rt {

MemoryManagement::MemoryManagement(llvm::LLVMContext &c, IRBuilder<> &b,
                                   ValueEncoder &v, LLVMTypes &t,
                                   VariableBindings<TypedValue> &vb,
                                   InvokeManager &i, DynamicConstructor &d)
    : context(c), builder(b), valueEncoder(v), types(t),
      variableBindingStack(vb), invoke(i), dynamicConstructor(d) {}

/* Applies memory operations (retains/releases) according to the guidance
   generated by the frontend. In the future, ( TODO ) a single retain/release
   call could be made with a counter (if appropriate runtime modification is
   done) */

void MemoryManagement::dynamicMemoryGuidance(
    const MemoryManagementGuidance &guidance) {
  auto name = guidance.variablename();
  auto change = guidance.requiredrefcountchange();

  for (word_t depth = variableBindingStack.stackDepth() - 1; depth >= 0;
       depth--) {
    auto val = variableBindingStack.find(name, depth);
    if (val) {
      while (change != 0) {
        if (change > 0) {
          dynamicRetain(*val);
          change--;
        } else {
          dynamicRelease(*val);
          change++;
        }
      }
      break;
    }
  }
}

void MemoryManagement::dynamicRetain(TypedValue &target) {
  if (target.type.isScalar() || target.type.isBoxedScalar())
    return;

  Metadata *metaPtr = dyn_cast<Metadata>(MDString::get(context, "retain"));
  MDNode *meta = MDNode::get(context, metaPtr);

#ifndef REFCOUNT_TRACING
  if (target.type.isDetermined()) {
    auto prepare =
        target.type.isBoxedPointer() ? valueEncoder.unbox(target) : target;
    Value *gepPtr = builder.CreateStructGEP(types.RT_objectTy, prepare.value, 0,
                                            "get_refcount");
    auto rmw = builder.CreateAtomicRMW(AtomicRMWInst::BinOp::Add, gepPtr,
                                       // TODO - 32/64 bit alignment
                                       builder.getInt32(1), MaybeAlign(),
                                       AtomicOrdering::Monotonic);
    if (auto *i = dyn_cast<Instruction>(rmw)) {
      i->setMetadata("memory_management", meta);
    }
    return;
  }
#endif

  TypedValue retain = invoke.invokeRuntime(
      "retain", nullptr, {ObjectTypeSet::all()}, {valueEncoder.box(target)});
  if (auto *i = dyn_cast<Instruction>(retain.value)) {
    i->setMetadata("memory_management", meta);
  }
}

TypedValue MemoryManagement::dynamicRelease(TypedValue &target) {
  if (target.type.isScalar() || target.type.isBoxedScalar())
    return dynamicConstructor.createBoolean(false);

  Metadata *metaPtr = dyn_cast<Metadata>(MDString::get(context, "release"));
  MDNode *meta = MDNode::get(context, metaPtr);

#ifndef REFCOUNT_TRACKING
  if (target.type.isDetermined()) {
    auto prepare =
        target.type.isBoxedPointer() ? valueEncoder.unbox(target) : target;
    Value *gepPtr = builder.CreateStructGEP(types.RT_objectTy, prepare.value, 0,
                                            "get_refcount");
    auto rmw = builder.CreateAtomicRMW(AtomicRMWInst::BinOp::Sub, gepPtr,
                                       // TODO - 32/64 bit alignment
                                       builder.getInt32(1), MaybeAlign(),
                                       AtomicOrdering::Release);
    if (auto *i = dyn_cast<Instruction>(rmw)) {
      i->setMetadata("memory_management", meta);
    }

    Value *condValue = builder.CreateICmpEQ(
        rmw, dynamicConstructor.createBoolean(true).value, "cmp_jj");
    Function *parentFunction = builder.GetInsertBlock()->getParent();
    BasicBlock *destroyBB =
        llvm::BasicBlock::Create(context, "destroy", parentFunction);
    BasicBlock *ignoreBB = llvm::BasicBlock::Create(context, "ignore");
    BasicBlock *mergeBB = llvm::BasicBlock::Create(context, "release_cont");

    builder.CreateCondBr(condValue, destroyBB, ignoreBB);
    builder.SetInsertPoint(destroyBB);
    builder.CreateFence(llvm::AtomicOrdering::Acquire, llvm::SyncScope::System);

    auto retValType = ObjectTypeSet(booleanType);
    invoke.invokeRuntime("Object_destroy", nullptr,
                         {ObjectTypeSet::all(), ObjectTypeSet(booleanType)},
                         {prepare, dynamicConstructor.createBoolean(true)});

    builder.CreateBr(mergeBB);

    parentFunction->insert(parentFunction->end(), ignoreBB);
    builder.SetInsertPoint(ignoreBB);
    builder.CreateBr(mergeBB);

    parentFunction->insert(parentFunction->end(), mergeBB);
    builder.SetInsertPoint(mergeBB);

    llvm::PHINode *phiNode = builder.CreatePHI(types.i1Ty, 2, "release_phi");
    phiNode->addIncoming(dynamicConstructor.createBoolean(true).value,
                         destroyBB);
    phiNode->addIncoming(dynamicConstructor.createBoolean(false).value,
                         ignoreBB);
    return TypedValue(ObjectTypeSet(booleanType), phiNode);
  }
#endif

  TypedValue release = invoke.invokeRuntime(
      "release", nullptr, {ObjectTypeSet::all()}, {valueEncoder.box(target)});
  if (auto *i = dyn_cast<Instruction>(release.value)) {
    i->setMetadata("memory_management", meta);
  }
  return release;
}
void MemoryManagement::dynamicIsReusable(TypedValue &target) {}

} // namespace rt
