(.contains "asdfasdsdasdsfs" "sdf")
(.contains "asfasdsdasdsfs" "sdf")
(.indexOf "asdfsd" "sdf")
(.indexOf "asdfsd" "sdf" 6)
(.indexOf "asdfsd" "sdf" 0)
(.replace "asdf" "f" "g")
(defn f [x] (.replace x "f" "g"))
(def g true)
(def h "eff")
(def i "afk")
(f (if g h i))
